-- =============================================================================
-- Fix cover-images storage RLS: drop any conflicting/duplicate policies
-- (including ones auto-generated by the dashboard bucket UI) and recreate
-- with explicit role scoping, which some Supabase Storage versions require.
-- =============================================================================

do $$
declare
  pol record;
begin
  for pol in
    select policyname
    from pg_policies
    where schemaname = 'storage' and tablename = 'objects'
  loop
    execute format('drop policy if exists %I on storage.objects', pol.policyname);
  end loop;
end $$;

-- Public read access to cover-images
create policy "Public read cover-images"
  on storage.objects for select
  to public
  using (bucket_id = 'cover-images');

-- Authenticated admins can upload
-- Uses public.is_admin() (SECURITY DEFINER) instead of querying site_admins
-- directly: site_admins has RLS enabled with no SELECT policy for
-- `authenticated`, so a direct subquery here always returns an empty set and
-- silently fails the check even for real admins. is_admin() bypasses that.
create policy "Admin upload cover images"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'cover-images'
    and public.is_admin()
  );

-- Authenticated admins can delete
create policy "Admin delete cover images"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'cover-images'
    and public.is_admin()
  );

-- Authenticated admins can update metadata
create policy "Admin update cover images"
  on storage.objects for update
  to authenticated
  with check (
    bucket_id = 'cover-images'
    and public.is_admin()
  );

-- Ensure the bucket itself is public + has the expected limits
update storage.buckets
set public = true,
    file_size_limit = 10485760,
    allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
where id = 'cover-images';
